// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppActivation.proto

package com.howbuy.uac.protobuf;

public final class AppActivation {
  private AppActivation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Activation extends
      com.google.protobuf.GeneratedMessage {
    // Use Activation.newBuilder() to construct.
    private Activation() {
      initFields();
    }
    private Activation(boolean noInit) {}
    
    private static final Activation defaultInstance;
    public static Activation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Activation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.uac.protobuf.AppActivation.internal_static_com_howbuy_uac_protobuf_Activation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.uac.protobuf.AppActivation.internal_static_com_howbuy_uac_protobuf_Activation_fieldAccessorTable;
    }
    
    // required string proid = 1;
    public static final int PROID_FIELD_NUMBER = 1;
    private boolean hasProid;
    private java.lang.String proid_ = "";
    public boolean hasProid() { return hasProid; }
    public java.lang.String getProid() { return proid_; }
    
    // required string imei = 2;
    public static final int IMEI_FIELD_NUMBER = 2;
    private boolean hasImei;
    private java.lang.String imei_ = "";
    public boolean hasImei() { return hasImei; }
    public java.lang.String getImei() { return imei_; }
    
    // required string guid = 3;
    public static final int GUID_FIELD_NUMBER = 3;
    private boolean hasGuid;
    private java.lang.String guid_ = "";
    public boolean hasGuid() { return hasGuid; }
    public java.lang.String getGuid() { return guid_; }
    
    // required string outletcode = 4;
    public static final int OUTLETCODE_FIELD_NUMBER = 4;
    private boolean hasOutletcode;
    private java.lang.String outletcode_ = "";
    public boolean hasOutletcode() { return hasOutletcode; }
    public java.lang.String getOutletcode() { return outletcode_; }
    
    // required string type = 5;
    public static final int TYPE_FIELD_NUMBER = 5;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // optional string custno = 6;
    public static final int CUSTNO_FIELD_NUMBER = 6;
    private boolean hasCustno;
    private java.lang.String custno_ = "";
    public boolean hasCustno() { return hasCustno; }
    public java.lang.String getCustno() { return custno_; }
    
    // optional string resolution = 7;
    public static final int RESOLUTION_FIELD_NUMBER = 7;
    private boolean hasResolution;
    private java.lang.String resolution_ = "";
    public boolean hasResolution() { return hasResolution; }
    public java.lang.String getResolution() { return resolution_; }
    
    // optional string agent = 8;
    public static final int AGENT_FIELD_NUMBER = 8;
    private boolean hasAgent;
    private java.lang.String agent_ = "";
    public boolean hasAgent() { return hasAgent; }
    public java.lang.String getAgent() { return agent_; }
    
    // required string version = 9;
    public static final int VERSION_FIELD_NUMBER = 9;
    private boolean hasVersion;
    private java.lang.String version_ = "";
    public boolean hasVersion() { return hasVersion; }
    public java.lang.String getVersion() { return version_; }
    
    // required string network = 10;
    public static final int NETWORK_FIELD_NUMBER = 10;
    private boolean hasNetwork;
    private java.lang.String network_ = "";
    public boolean hasNetwork() { return hasNetwork; }
    public java.lang.String getNetwork() { return network_; }
    
    // required string appversion = 11;
    public static final int APPVERSION_FIELD_NUMBER = 11;
    private boolean hasAppversion;
    private java.lang.String appversion_ = "";
    public boolean hasAppversion() { return hasAppversion; }
    public java.lang.String getAppversion() { return appversion_; }
    
    // optional string ext = 12;
    public static final int EXT_FIELD_NUMBER = 12;
    private boolean hasExt;
    private java.lang.String ext_ = "";
    public boolean hasExt() { return hasExt; }
    public java.lang.String getExt() { return ext_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasProid) return false;
      if (!hasImei) return false;
      if (!hasGuid) return false;
      if (!hasOutletcode) return false;
      if (!hasType) return false;
      if (!hasVersion) return false;
      if (!hasNetwork) return false;
      if (!hasAppversion) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProid()) {
        output.writeString(1, getProid());
      }
      if (hasImei()) {
        output.writeString(2, getImei());
      }
      if (hasGuid()) {
        output.writeString(3, getGuid());
      }
      if (hasOutletcode()) {
        output.writeString(4, getOutletcode());
      }
      if (hasType()) {
        output.writeString(5, getType());
      }
      if (hasCustno()) {
        output.writeString(6, getCustno());
      }
      if (hasResolution()) {
        output.writeString(7, getResolution());
      }
      if (hasAgent()) {
        output.writeString(8, getAgent());
      }
      if (hasVersion()) {
        output.writeString(9, getVersion());
      }
      if (hasNetwork()) {
        output.writeString(10, getNetwork());
      }
      if (hasAppversion()) {
        output.writeString(11, getAppversion());
      }
      if (hasExt()) {
        output.writeString(12, getExt());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getProid());
      }
      if (hasImei()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getImei());
      }
      if (hasGuid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getGuid());
      }
      if (hasOutletcode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getOutletcode());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getType());
      }
      if (hasCustno()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getCustno());
      }
      if (hasResolution()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getResolution());
      }
      if (hasAgent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getAgent());
      }
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getVersion());
      }
      if (hasNetwork()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getNetwork());
      }
      if (hasAppversion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getAppversion());
      }
      if (hasExt()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getExt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.uac.protobuf.AppActivation.Activation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.uac.protobuf.AppActivation.Activation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.uac.protobuf.AppActivation.Activation result;
      
      // Construct using com.howbuy.uac.protobuf.AppActivation.Activation.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.uac.protobuf.AppActivation.Activation();
        return builder;
      }
      
      protected com.howbuy.uac.protobuf.AppActivation.Activation internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.uac.protobuf.AppActivation.Activation();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.uac.protobuf.AppActivation.Activation.getDescriptor();
      }
      
      public com.howbuy.uac.protobuf.AppActivation.Activation getDefaultInstanceForType() {
        return com.howbuy.uac.protobuf.AppActivation.Activation.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.uac.protobuf.AppActivation.Activation build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.uac.protobuf.AppActivation.Activation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.uac.protobuf.AppActivation.Activation buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.uac.protobuf.AppActivation.Activation returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.uac.protobuf.AppActivation.Activation) {
          return mergeFrom((com.howbuy.uac.protobuf.AppActivation.Activation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.uac.protobuf.AppActivation.Activation other) {
        if (other == com.howbuy.uac.protobuf.AppActivation.Activation.getDefaultInstance()) return this;
        if (other.hasProid()) {
          setProid(other.getProid());
        }
        if (other.hasImei()) {
          setImei(other.getImei());
        }
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasOutletcode()) {
          setOutletcode(other.getOutletcode());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCustno()) {
          setCustno(other.getCustno());
        }
        if (other.hasResolution()) {
          setResolution(other.getResolution());
        }
        if (other.hasAgent()) {
          setAgent(other.getAgent());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasNetwork()) {
          setNetwork(other.getNetwork());
        }
        if (other.hasAppversion()) {
          setAppversion(other.getAppversion());
        }
        if (other.hasExt()) {
          setExt(other.getExt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setProid(input.readString());
              break;
            }
            case 18: {
              setImei(input.readString());
              break;
            }
            case 26: {
              setGuid(input.readString());
              break;
            }
            case 34: {
              setOutletcode(input.readString());
              break;
            }
            case 42: {
              setType(input.readString());
              break;
            }
            case 50: {
              setCustno(input.readString());
              break;
            }
            case 58: {
              setResolution(input.readString());
              break;
            }
            case 66: {
              setAgent(input.readString());
              break;
            }
            case 74: {
              setVersion(input.readString());
              break;
            }
            case 82: {
              setNetwork(input.readString());
              break;
            }
            case 90: {
              setAppversion(input.readString());
              break;
            }
            case 98: {
              setExt(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string proid = 1;
      public boolean hasProid() {
        return result.hasProid();
      }
      public java.lang.String getProid() {
        return result.getProid();
      }
      public Builder setProid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProid = true;
        result.proid_ = value;
        return this;
      }
      public Builder clearProid() {
        result.hasProid = false;
        result.proid_ = getDefaultInstance().getProid();
        return this;
      }
      
      // required string imei = 2;
      public boolean hasImei() {
        return result.hasImei();
      }
      public java.lang.String getImei() {
        return result.getImei();
      }
      public Builder setImei(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasImei = true;
        result.imei_ = value;
        return this;
      }
      public Builder clearImei() {
        result.hasImei = false;
        result.imei_ = getDefaultInstance().getImei();
        return this;
      }
      
      // required string guid = 3;
      public boolean hasGuid() {
        return result.hasGuid();
      }
      public java.lang.String getGuid() {
        return result.getGuid();
      }
      public Builder setGuid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGuid = true;
        result.guid_ = value;
        return this;
      }
      public Builder clearGuid() {
        result.hasGuid = false;
        result.guid_ = getDefaultInstance().getGuid();
        return this;
      }
      
      // required string outletcode = 4;
      public boolean hasOutletcode() {
        return result.hasOutletcode();
      }
      public java.lang.String getOutletcode() {
        return result.getOutletcode();
      }
      public Builder setOutletcode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOutletcode = true;
        result.outletcode_ = value;
        return this;
      }
      public Builder clearOutletcode() {
        result.hasOutletcode = false;
        result.outletcode_ = getDefaultInstance().getOutletcode();
        return this;
      }
      
      // required string type = 5;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // optional string custno = 6;
      public boolean hasCustno() {
        return result.hasCustno();
      }
      public java.lang.String getCustno() {
        return result.getCustno();
      }
      public Builder setCustno(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCustno = true;
        result.custno_ = value;
        return this;
      }
      public Builder clearCustno() {
        result.hasCustno = false;
        result.custno_ = getDefaultInstance().getCustno();
        return this;
      }
      
      // optional string resolution = 7;
      public boolean hasResolution() {
        return result.hasResolution();
      }
      public java.lang.String getResolution() {
        return result.getResolution();
      }
      public Builder setResolution(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasResolution = true;
        result.resolution_ = value;
        return this;
      }
      public Builder clearResolution() {
        result.hasResolution = false;
        result.resolution_ = getDefaultInstance().getResolution();
        return this;
      }
      
      // optional string agent = 8;
      public boolean hasAgent() {
        return result.hasAgent();
      }
      public java.lang.String getAgent() {
        return result.getAgent();
      }
      public Builder setAgent(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAgent = true;
        result.agent_ = value;
        return this;
      }
      public Builder clearAgent() {
        result.hasAgent = false;
        result.agent_ = getDefaultInstance().getAgent();
        return this;
      }
      
      // required string version = 9;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public java.lang.String getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = getDefaultInstance().getVersion();
        return this;
      }
      
      // required string network = 10;
      public boolean hasNetwork() {
        return result.hasNetwork();
      }
      public java.lang.String getNetwork() {
        return result.getNetwork();
      }
      public Builder setNetwork(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNetwork = true;
        result.network_ = value;
        return this;
      }
      public Builder clearNetwork() {
        result.hasNetwork = false;
        result.network_ = getDefaultInstance().getNetwork();
        return this;
      }
      
      // required string appversion = 11;
      public boolean hasAppversion() {
        return result.hasAppversion();
      }
      public java.lang.String getAppversion() {
        return result.getAppversion();
      }
      public Builder setAppversion(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppversion = true;
        result.appversion_ = value;
        return this;
      }
      public Builder clearAppversion() {
        result.hasAppversion = false;
        result.appversion_ = getDefaultInstance().getAppversion();
        return this;
      }
      
      // optional string ext = 12;
      public boolean hasExt() {
        return result.hasExt();
      }
      public java.lang.String getExt() {
        return result.getExt();
      }
      public Builder setExt(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasExt = true;
        result.ext_ = value;
        return this;
      }
      public Builder clearExt() {
        result.hasExt = false;
        result.ext_ = getDefaultInstance().getExt();
        return this;
      }

	@Override
	protected FieldAccessorTable internalGetFieldAccessorTable() {
		// TODO Auto-generated method stub
		return null;
	}
      
      // @@protoc_insertion_point(builder_scope:com.howbuy.uac.protobuf.Activation)
    }
    
    static {
      defaultInstance = new Activation(true);
      com.howbuy.uac.protobuf.AppActivation.internalForceInit();
      defaultInstance.initFields();
    }

	@Override
	protected com.google.protobuf.Message.Builder newBuilderForType(
			BuilderParent parent) {
		// TODO Auto-generated method stub
		return null;
	}
    
    // @@protoc_insertion_point(class_scope:com.howbuy.uac.protobuf.Activation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_howbuy_uac_protobuf_Activation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_howbuy_uac_protobuf_Activation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AppActivation.proto\022\027com.howbuy.uac.pr" +
      "otobuf\"\317\001\n\nActivation\022\r\n\005proid\030\001 \002(\t\022\014\n\004" +
      "imei\030\002 \002(\t\022\014\n\004guid\030\003 \002(\t\022\022\n\noutletcode\030\004" +
      " \002(\t\022\014\n\004type\030\005 \002(\t\022\016\n\006custno\030\006 \001(\t\022\022\n\nre" +
      "solution\030\007 \001(\t\022\r\n\005agent\030\010 \001(\t\022\017\n\007version" +
      "\030\t \002(\t\022\017\n\007network\030\n \002(\t\022\022\n\nappversion\030\013 " +
      "\002(\t\022\013\n\003ext\030\014 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_howbuy_uac_protobuf_Activation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_howbuy_uac_protobuf_Activation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_howbuy_uac_protobuf_Activation_descriptor,
              new java.lang.String[] { "Proid", "Imei", "Guid", "Outletcode", "Type", "Custno", "Resolution", "Agent", "Version", "Network", "Appversion", "Ext", },
              com.howbuy.uac.protobuf.AppActivation.Activation.class,
              com.howbuy.uac.protobuf.AppActivation.Activation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
